name: CI

on:
  push:
    branches:
      - 'feat/**'
      - 'develop'
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "22.14"
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/